FROM continuumio/miniconda3

ADD requirements.txt /env/requirements.txt
RUN pip install -r /env/requirements.txt

RUN python -m textblob.download_corpora
ADD . /app
WORKDIR /app

ENTRYPOINT ["python3", "app.py"]
